site_name: Recipe Book
site_url: https://Jones-Good-Ass-Recipe-book.com
use_directory_urls: false
nav:
  - Home: 'index.md'
  - Tags: 'tags.md'
markdown_extensions:
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
